import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowUpRight, BookOpen, Gamepad2, Sparkles, Tv } from 'lucide-react';
import { PageLoader } from './DataState';
import { useDashboardContentDistribution, useDashboardPopular, useDashboardStats } from '../hooks/queries/dashboard';

const labels: Record<string, string> = { Articles: '文章', Diary: '日记', Photos: '照片', Anime: '追番', Games: '游戏' };

const SystemDashboard: React.FC = () => {
  const { data: stats, isLoading: statsLoading, error } = useDashboardStats();
  const { data: popular, isLoading: popularLoading } = useDashboardPopular();
  const { data: distribution, isLoading: distributionLoading } = useDashboardContentDistribution();
  if (statsLoading || popularLoading || distributionLoading) return <PageLoader className="min-h-[360px]" />;
  if (error || !stats) return <div className="rounded-xl border border-red-200 bg-red-50 p-5 text-red-700 dark:border-red-900/50 dark:bg-red-950/30 dark:text-red-300">内容脉搏暂时无法加载，请稍后再试。</div>;
  const trend = stats.trafficTrend ?? [];
  const maxTraffic = Math.max(...trend.map(item => item.pageViews), 1);
  const cards = [{ label: '文章', value: stats.contentStats.articles, icon: BookOpen, path: '/posts' }, { label: '追番', value: stats.contentStats.anime, icon: Tv, path: '/anime' }, { label: '游戏', value: stats.contentStats.games, icon: Gamepad2, path: '/games' }];
  return <div className="space-y-6">
    <section className="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm dark:border-white/10 dark:bg-[#101010] md:p-8"><p className="font-mono text-xs tracking-[0.18em] text-neon">SITE PULSE</p><div className="mt-3 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><h2 className="text-3xl font-bold text-ink dark:text-white">这里最近发生了什么</h2><p className="mt-2 text-sm text-gray-600 dark:text-gray-400">从文章、追番和游戏记录里，挑一条感兴趣的线索开始探索。</p></div><div className="flex gap-6"><div><p className="text-2xl font-bold text-ink dark:text-white">{stats.contentStats.totalContent}</p><p className="text-xs text-gray-500">内容条目</p></div><div><p className="text-2xl font-bold text-ink dark:text-white">{stats.totalRequests}</p><p className="text-xs text-gray-500">累计访问</p></div></div></div></section>
    <section className="grid gap-4 md:grid-cols-3">{cards.map(({ label, value, icon: Icon, path }) => <Link key={label} to={path} className="group rounded-xl border border-gray-200 bg-white p-5 transition-colors hover:border-neon dark:border-white/10 dark:bg-[#101010]"><Icon size={19} className="text-neon" /><div className="mt-5 flex items-end justify-between"><div><p className="text-3xl font-bold text-ink dark:text-white">{value}</p><p className="mt-1 text-sm text-gray-600 dark:text-gray-400">{label}记录</p></div><ArrowUpRight size={18} className="text-gray-400 group-hover:text-neon" /></div></Link>)}</section>
    <section className="grid gap-6 lg:grid-cols-2"><div className="rounded-xl border border-gray-200 bg-white p-5 dark:border-white/10 dark:bg-[#101010]"><div className="flex items-center gap-2"><Sparkles size={18} className="text-neon" /><h3 className="font-semibold text-ink dark:text-white">内容地图</h3></div><div className="mt-5 space-y-4">{distribution?.map(item => <div key={item.label}><div className="mb-1 flex justify-between text-sm"><span className="text-gray-600 dark:text-gray-300">{labels[item.label] ?? item.label}</span><span className="font-mono text-ink dark:text-white">{item.count}</span></div><div className="h-2 overflow-hidden rounded-full bg-gray-100 dark:bg-white/10"><div className="h-full rounded-full bg-neon" style={{ width: `${item.percentage}%` }} /></div></div>)}</div></div><div className="rounded-xl border border-gray-200 bg-white p-5 dark:border-white/10 dark:bg-[#101010]"><h3 className="font-semibold text-ink dark:text-white">最近 7 天访问</h3>{trend.length ? <div className="mt-7 flex h-36 items-end gap-2">{trend.map(item => <div key={item.date} className="flex flex-1 flex-col items-center gap-2"><div className="w-full rounded-t bg-neon/70" style={{ height: `${Math.max((item.pageViews / maxTraffic) * 100, 4)}%` }} title={`${item.date}: ${item.pageViews} 次访问`} /><span className="text-[10px] text-gray-500">{item.date.slice(5)}</span></div>)}</div> : <p className="mt-5 text-sm leading-6 text-gray-500 dark:text-gray-400">访问统计正在从今天开始积累，稍后回来查看趋势。</p>}</div></section>
    <section className="rounded-xl border border-gray-200 bg-white dark:border-white/10 dark:bg-[#101010]"><div className="border-b border-gray-100 p-5 dark:border-white/10"><h3 className="font-semibold text-ink dark:text-white">热门文章</h3></div>{popular?.posts?.length ? popular.posts.map((post, index) => <Link key={post.id} to={`/posts/${post.id}`} className="group flex items-center gap-4 border-b border-gray-100 px-5 py-4 last:border-0 hover:bg-gray-50 dark:border-white/10 dark:hover:bg-white/5"><span className="font-mono text-sm text-neon">{String(index + 1).padStart(2, '0')}</span><span className="min-w-0 flex-1 truncate text-sm font-medium text-ink group-hover:text-neon dark:text-white">{post.title}</span><span className="text-xs text-gray-500">{post.viewCount ?? 0} 次阅读</span><ArrowUpRight size={16} className="text-gray-400 group-hover:text-neon" /></Link>) : <p className="p-5 text-sm text-gray-500">文章数据正在积累。</p>}</section>
  </div>;
};
export default SystemDashboard;
